spring:
  application:
    name: gateway
  cloud:
    gateway:
#      routes:
#        - id: route_1
#          uri: http://httpbin.org
#          predicates:
#            - Path=/get
      discovery:
        locator:
          # 开启自动代理
          enabled: true

server:
  port: 11116

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka

logging:
  level:
    org.springframework.cloud.gateway: debug